spring:
  application:
    name: book-service
  profiles:
    active: test
  cloud:
    config:
      enabled: false
    vault:
      enabled: true
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: book-service
        default-context: default
      fail-fast: true
  config:
    import: optional:vault://
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 0

grpc:
  server:
    port: 9876