spring:
  application:
    name: book-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:BOOKDB  # 'xe' yerine kendi servis adını yazmalısın
    username: system
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect # Dialect belirtmek iyi bir pratiktir

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{traceId},%X{spanId}]"
